parameters:
    locale: 'fr'
    app_locales: ['%locale%']
    doctrine_behaviors_blameable_user_entity: 'App\Entity\User'
    mollie_api_key: '%env(MOLLIE_API_KEY)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\EventSubscriber\AppointmentSubscriber:
        tags:
            - { name: doctrine.event_subscriber }